### ISSUE TITLE
pip install is missing a directory

### ISSUE THREAD

**Issue by calvinqi** [Tiiiger/QPyTorch#18]
Thanks for creating this! Been trying to use it for some experiments, and found that the `qtorch/quant/quant_cpu` and `qtorch/quant/quant_cuda` libraries are missing from the pip installation. 

For example, in python, when I write
```python
from qtorch.quant import Quantizer
```
I get the error 
```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/calvinq/miniconda3/envs/envname/lib/python3.7/site-packages/qtorch/quant/quant_cpu/quant_cpu.cpp'
```
And when I list what's in the directory `ls users/calvinq/.../qtorch/quant/` all I get are:
```
__init__.py       __pycache__       quant_function.py quant_module.py
```

Any idea on how to fix this? Thank you so much :)

**Comment by Tiiiger** [comment]
@calvinqi Hi Thank you for your interest. I'll fix this by tonight.

**Comment by Tiiiger** [comment]
@calvinqi 

please help try
```bash
pip install qtorch==0.1.1
```

let me know if it works for you

**Comment by calvinqi** [comment]
Works like a charm. Thank you so much!
