### ISSUE TITLE
KeyError: 'momentum' in optim_low

### ISSUE THREAD

**Issue by calvinqi** [Tiiiger/QPyTorch#20]
Hi! I encountered a bit of a bug. When trying to use OptimLP with Adam, line 97 in `optim_low.py` tries to access the key 'momentum' in the parameter group, but Adam does not have this field so an error occurs. Maybe this could include a check to see `if 'momentum' in group`?

Here's are examples:

For SGD,
```python
optimizer = SGD(model.parameters(), lr=0.05)
optimizer = OptimLP(optimizer,
                    weight_quant=weight_quant,
                    grad_quant=grad_quant,
                    momentum_quant=momentum_quant,
                    acc_quant=acc_quant
)
```
```
Output: dict_keys(['params', 'lr', 'betas', 'eps', 'weight_decay', 'amsgrad'])
```

For Adam,
```python
optimizer = Adam(model.parameters())
optimizer = OptimLP(optimizer,
                    weight_quant=weight_quant,
                    grad_quant=grad_quant,
                    momentum_quant=momentum_quant,
                    acc_quant=acc_quant
)
```
```
Output: dict_keys(['params', 'lr', 'betas', 'eps', 'weight_decay', 'amsgrad'])
```

**Comment by Tiiiger** [comment]
Hi @calvinqi, 

indeed a bug. Adam stores the momentum of gradient as 'exp_avg' and the momentum of the squared of the gradient as 'exp_avg_sq'. So accessing 'momentum' would cause a problem. 

I will fix this tonight. stay tuned.

**Comment by Tiiiger** [comment]
@calvinqi I have pushed the changes in 7962268.
