### ISSUE TITLE
How can I print the gradient of each layer?

### ISSUE THREAD

**Issue by Maoquan232** [Tiiiger/QPyTorch#22]
Hi, I want to print the error before and after quantization in the bakcward，I am wondering Qpytorch can make it.
Thanks~

**Comment by Tiiiger** [comment]
Hi @Maoquan232, 

you can write the print function before/after this line https://github.com/Tiiiger/QPyTorch/blob/master/qtorch/quant/quant_function.py#L166. 

Let me know if this works for you.

**Comment by Maoquan232** [comment]
Hi, thanks.
I didnt test it in QPytorch，I tested in my code which defined the forward and backward function
`class QuantizeGrad(InplaceFunction):

    @classmethod
    def forward(cls, ctx, input,min_value=None, max_value=None):
        ctx.min_value = min_value
        ctx.max_value = max_value
        return input

    @staticmethod
    def backward(ctx, grad_output):
        if ctx.min_value is None:
            min_value = float(grad_output.min())
        else:
            min_value = ctx.min_value
        if ctx.max_value is None:
            max_value = float(grad_output.max())
        else:
            max_value = ctx.max_value

	print(grad_output)
        grad_input = QuanError().apply(grad_output,,min_value,max_value)
	print(grad_input)
        return grad_input, None, None`

well, it works for me.  
The issue comes from that I want to debug the backward of Pytorch to see what happens in each layer. I can do it in Caffe while Pytorch is wrapped with python and the backward seems invisible.
 if you have any suggestions, let me konw.
Thanks a lot

**Comment by Tiiiger** [comment]
looks good to me : )

**Comment by Maoquan232** [comment]
Hi, Tiiiger, do you have any suggestions about debug the backward?
