### ISSUE TITLE
cast error for float->half

### ISSUE THREAD

**Issue by drcut** [Tiiiger/QPyTorch#24]
Hi,everyone
I have use QPytorch to do naive cast from float(1,8,23) to half(1,5,10). However, I found the result is different from pytorch's cast.
Here is the test code.
`

import torch
from qtorch.quant import Quantizer
from qtorch import FloatingPoint
torch.manual_seed(25)
bit_16 = FloatingPoint(exp=5, man=10)
weight_quant = Quantizer(forward_number=bit_16, backward_number=None,
                        forward_rounding="nearest", backward_rounding="nearest").cuda()
a = torch.rand([1000]).cuda()
b = torch.rand([1000]).cuda()
print("round:..............")
a = a[314]
res1 = weight_quant(a)
res2 = a.half().float()
assert res1.equal(res2)

`
It seems when I cast a value, which will be subnormal in my DIY precision, and be normal in float32, it will cause this error.

**Comment by Tiiiger** [comment]
hi @drcut, my implementation, unfortunately, does not handle subnorms. so a difference would be expected.
