### ISSUE TITLE
Confuse about WAGE reproduction

### ISSUE THREAD

**Issue by tuanho27** [Tiiiger/QPyTorch#25]
Hi there,

As the WAGE paper mention, they used the integer number value for W,A,G,E with 2,8,8,8 bits respectively. However, your implementation used fix-point value for that numbers, is there any explanation for that or I misunderstand something?
Thanks,

**Comment by Tiiiger** [comment]
Hi the WAGE paper maps these integer numbers to a fixed range, which is equivalent with using fixed point. You can compare to the original implementation https://github.com/boluoweifenda/WAGE/blob/master/source/Quantize.py and observe the similarity.
