### ISSUE TITLE
CFAR10 example stuck at 10% accuracy 

### ISSUE THREAD

**Issue by massimogiordano** [Tiiiger/QPyTorch#26]
I run the example I found in the documentation: (https://qpytorch.readthedocs.io/en/latest/examples/tutorial/CIFAR10_Low_Precision_Training_Example.html)

But the accuracy is 10% and it does not increase even if I increase the number of epochs. 

Is there something wrong in the example or I am missing something?

Thanks

**Comment by Tiiiger** [comment]
Hi @massimogiordano, thank you for letting me know. 

Yes there are two mistakes with the previous example.

- this quantization setting (taken from the IBM 8-bit floating point training paper) is designed for ResNet. So I change the example model to a PreResNet20
- we need to apply loss scaling, as indicated in the original paper

I have update the example, please see https://github.com/Tiiiger/QPyTorch/blob/master/examples/tutorial/CIFAR10_Low_Precision_Training_Example.ipynb
