### ISSUE TITLE
Compiler not compatible issue

### ISSUE THREAD

**Issue by calvinqi** [Tiiiger/QPyTorch#27]
Hi! I've encountered an issue when importing this package on certain CentOS machines.

Installing qtorch works fine, but whenever I try to import a particular function, such as 
```python
from qtorch.quant import fixed_point_quantize
```
I get the following long error:
```
                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!
```
Then none of the library's functions work and they'll result in a segfault+crash. Any idea how this might be fixed? On my ubuntu machine this error does not come up, but for certain experiments I'm running it has to be on the CentOS systems so there's no way to avoid this error for me.

Thank you!

**Comment by Tiiiger** [comment]
Hi, can you let me know your g++ version on both environments?

**Comment by Tiiiger** [comment]
@calvinqi hi there. are you still seeing this problem?

**Comment by calvinqi** [comment]
Hi! My gcc version is 4.8.5 on the CentOS machines. On the Ubuntu it's 7.4.0

**Comment by Tiiiger** [comment]
Hi, then sounds like if you update the gcc according to pytorch requirements, the issue should be resolved. 

Just to give you more context, QPyTorch is essentially a set of PyTorch cuda (and c++) extensions. so if they are not built correctly, following PyTorch's requirements, I am not sure what behaviors to expected. In that case, seg fault+crash doesn't sound to surprising although personally I havn't experienced it.

I tried to look up for a page regarding the gcc version requirements but couldn't find any. I am also not very familiar with CentOS. Thus, unfortunately the best I can tell is to look into this version mismatch. 

Hope you can solve it. I will add a warning about this requirement in README. Closing for now but feel free to reopen.

**Comment by Tiiiger** [comment]
Actually I found it. You need gcc >= 4.9

See: https://pytorch.org/tutorials/advanced/cpp_extension.html

**Comment by SimlaBurcu** [comment]
Hello,
My machine has the following setting but I am getting the same warning

CentOS Linux release 7.3.1611 (Core)
gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
