### ISSUE TITLE
Incorrect maximum exponent value

### ISSUE THREAD

**Issue by ynahshan** [Tiiiger/QPyTorch#29]
Hi. According to my understanding for k bit exponent maximal exponent value should be calculated as following (2^k - 1) - (2^(k - 1) - 1) = 2^(k-1). 
In your code I see max exponent calculated ((1 << (exp_bits-1))-1) + 127 which is equivalent to 2^(k-1) - 1.
For instance at (1,4,3) configuration (sign, exp, mantissa) maximal representable number should be:
2^8 * 1.875 = 480
but with qtorch I get
2^7 * 1.875 = 240

Could you please clarify if this is bug or explain the rational behind reduced upper limit.
Thanks.

**Comment by Tiiiger** [comment]
hi @ynahshan, sorry for the late reply. 

I think your understanding is correct. This is probably a bug. I'll push a fix soon.

**Comment by Tiiiger** [comment]
I am closing this but feel free to continue the thread
