### ISSUE TITLE
Non uniform quantization

### ISSUE THREAD

**Issue by Msabih** [Tiiiger/QPyTorch#30]
Is there a way to do non uniform quantization woth qtorch ?

**Comment by Tiiiger** [comment]
hi @Msabih , thank you for your interest in QPyTorch. 

If by Non-uniform quantization you mean something like quantizing onto a log-scale, then no, this is  nor currently supported in QPyTorch. Unfortunately I am also not an expert on this so probably won t implement it in the near future. 

However, if by non-uniform quantization you mean anything other than fixed-point quantization, i.e. quantizing onto a uniform grid within a given numerical range, then yes, QPyTorch supports floating point quantization and block fixed point quantization. 

I am not sure which of the above questions you are asking but I hope this resolve your confusion.
