### ISSUE TITLE
IMAGENET12

### ISSUE THREAD

**Issue by Amin-Azar** [Tiiiger/QPyTorch#31]
What are the steps to run the lp_train test with IMAGENET12?

**Comment by Tiiiger** [comment]
hi @Amin-Azar thank you for your interest. 

I think if you specify `--dataset` and `--data-path` in the argument the code should run (https://github.com/Tiiiger/QPyTorch/blob/master/examples/lp_train/train.py#L17)

You will need to set other hyperparameters using your own judgment. I don't have a good set of hyperparameters at hand.
