### ISSUE TITLE
Does sequential_lower quantize layer weights?

### ISSUE THREAD

**Issue by srcarroll** [Tiiiger/QPyTorch#33]
I wouldn't call this an issue.  It's more a question and I'm not sure where else to ask.  Does sequential_lower also quantize the layer weights or does it only quantize the outputs of corresponding layers?  My particular use case would be to train a network in full precision and then convert the model to low precision for inference.  I know I can manually convert the weights myself, but it would be nice if sequential_lower did that.  By looking at the code and printing out weights, it looks like it doesn't but please correct me if I'm wrong.  Thanks in advance for your reply.

**Comment by Tiiiger** [comment]
hi @srcarroll thank you for your interest in this repo. 

`sequential_lower` helps you insert quantizers into the network and these quantizers quantize the activations of each layer.
