### ISSUE TITLE
Grad quantization doesn't work for sparse tensors

### ISSUE THREAD

**Issue by srcarroll** [Tiiiger/QPyTorch#35]
Hi.  I was wondering if you were aware that quantizing gradients doesn't work for sparse tensors?  This is because x.contiguous() is used and sparse tensors do not have "is_contiguous".  Is there a reason for using contiguous?  Do you have any suggestions for making this work for sparse tensors?  Thanks in advance.

**Comment by Tiiiger** [comment]
hi @srcarroll my CUDA kernels wouldn't work if the tensors are sparse. This means that at least in the near future, this repo wouldn't support sparse tensor quantization.
