### ISSUE TITLE
How to import CPU Version on Quantizier?

### ISSUE THREAD

**Issue by 20171166** [Tiiiger/QPyTorch#36]
from qtorch.quant import Quantizer, quantizer doesn't work saying which : no hipcc in /PATH and I use CentOS 7.6.
It seems that Quatnizer for CPU Version have another name or I miss something.
Do you have a solution for this problem?

**Comment by 20171166** [comment]
It works on my labtop. sorry

**Comment by 20171166** [comment]
The problem is that QPytorch thinks that there is a AMD GPU and find PATH and tries to resolve where is hip compiler which actually doesn't exist.

**Comment by tianyi-asapp** [comment]
hi @20171166 , 

Actually I am not aware of this problem. I am also not very sure how best to fix it. Did you find a fix that works for you?

**Comment by Tiiiger** [comment]
hi @20171166 ,
Actually I am not aware of this problem. I am also not very sure how best to fix it. Did you find a fix that works for you?

**Comment by 20171166** [comment]
> hi @20171166 ,
> Actually I am not aware of this problem. I am also not very sure how best to fix it. Did you find a fix that works for you?

Actually I don't fix it. The thing that I'm sure is Qtorch tries to use GPU for some reasons and investigate all the PATH registered by .bashrc and the other files.
