### ISSUE TITLE
Extended version for Posit; Crashing in 'nsize = odd number"

### ISSUE THREAD

**Issue by Mamrez** [Tiiiger/QPyTorch#38]
Hi,

I've been working with low-precision CIFAR-10 training, and I used Posit numbers (bit_8 = Posit(nsize, es)). However, I realized that setting 'nsize' to an 'odd' number leads to an unexpected crash. It works for nsize = 10, 8, and 6, but whenever I tried nsize = 9 or 7 the crash happens in training.
[I am using Google Colab, and everything is fine for Floating point numbers].

**Such a great work! Thanks.

**Comment by Tiiiger** [comment]
hi @Mamrez 

what is Posit numbers?

**Comment by Mamrez** [comment]
Oh, "minhhn2910/QPyTorch" was forked from this repository and I though that the authors were the same. So this question is not related here.

**Comment by Tiiiger** [comment]
closing for now if this is not related to this repo.
