### ISSUE TITLE
no module named 'quant_cpu'

### ISSUE THREAD

**Issue by smsskil** [Tiiiger/QPyTorch#39]
Hi, 
when I run "from qtorch.quant import Quantizer, quantizer" here report an error

**/usr/lib/python3.6/imp.py in find_module(name, path)
    295         break  # Break out of outer loop when breaking out of inner loop.
    296     else:
--> 297         raise ImportError(_ERR_MSG.format(name), name=name)
    298 
    299     encoding = None

ImportError: No module named 'quant_cpu'**

It has the same problem in 0.1.1 and 0.2.0.  How to fix it?

**Comment by Tiiiger** [comment]
Hi @smsskil 

I am not entirely sure. Did you install the package through pip or from source?

**Comment by smsskil** [comment]
> Hi @smsskil
> 
> I am not entirely sure. Did you install the package through pip or from source?

Hi @Tiiiger 

Now I figure out where caused the error.  It's due to some dependencies.
Need to install gcc g++ before using the API.

Thanks
