### ISSUE TITLE
optim_low breaks if some parameter in the model has None gradient

### ISSUE THREAD

**Issue by kamikazekartik** [Tiiiger/QPyTorch#40]
In the `step()` method [here](https://github.com/Tiiiger/QPyTorch/blob/master/qtorch/optim/optim_low.py#L78), if `p.grad = None`, then this line will break causing the optimizer to crash. However, in several Deep Learning applications, it is common to have some parameters within a layer or even whole layers to be frozen. QPyTorch's optimizer would not be applicable to these cases.

PyTorch's default optimizer has a simple and elegant solution which is to just skip these parameters treating `None` has equivalent to `0` gradient. We have implemented this solution [here](https://github.com/kamikazekartik/cs744_assignments/blob/master/project/custom_optim_low.py#L78). I would like to propose this change to QPyTorch as well.

**Comment by Tiiiger** [comment]
hi @kamikazekartik thank you for your suggestion! if you can help fix it and submit a PR, I am happy to merge it. Otherwise it might take a while before I get to it.

**Comment by kamikazekartik** [comment]
Sounds good @Tiiiger! It's just a few lines of code, so I'll make the change and create a PR later today.
