### ISSUE TITLE
Question about float quantization

### ISSUE THREAD

**Issue by danielholanda** [Tiiiger/QPyTorch#42]
Hi,

The minimum and maximum values you can achieve with float numbers in this implementation seem to be different from IEEE-754-like representations. I assume that you are sacrificing some precision to avoid the computation of subnormal values. Is that correct? 

Could you please clarify if this is a problem in the implementation or if this was a design decision (which causes values close to zero to be poorly represented)?

Here is my understanding of this issue:

Let's assume that our exponent is 2 bits and our mantissa is also 2 bits

**Exponent:**
Usually, the exponent should be able to go from -1 (00) to 2 (11). 
In this QPytorch implementation, it goes from -2 (00) to 1(11).

Usually, if the exponent is zero, we will use a denormalized mantissa.
In this QPytorch implementation, if the exponent is zero, the output is also zero (regardless of the mantissa).

**Mantissa:**
The mantissa has an invisible leading bit, meaning that it varies between 1 and ~2.
For both implementations, if we have 2 bits in the mantissa, our mantissa should vary between 1 (1.00) and 1.75 (1.11) in steps of 0.25.

Here are the numbers that would be representable using the usual representation:
[-0.0, -0.25, -0.5, -0.75, -1.0, -1.25, -1.5, -1.75, -2.0, -2.5, -3.0, -3.5, -4.0, -5.0, -6.0, -7.0, 0.0, 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0, 2.5, 3.0, 3.5, 4.0, 5.0, 6.0, 7.0]

Here are the numbers representable in this QPytorch implementation (without subnormal values):
[-3.5, -3.0, -2.5, -2.0, -1.75, -1.5, -1.25, -1.0, -0.875, -0.75, -0.625, -0.5, 0.0, 0.5, 0.625, 0.75, 0.875, 1.0, 1.25, 1.5, 1.75, 2.0, 2.5, 3.0, 3.5]

Code:
```
import torch
import numpy as np
from qtorch.quant import *

def test_float():
    # Configurations
    exp, man = 2,2
    d="cpu"
    r="nearest"

    # Get min and max values representable
    a_max_pos =  (2 ** (2 ** (exp - 1))) * (1 - 2 ** (-man - 1))
    a_max_neg = -(2 ** (2 ** (exp - 1))) * (1 - 2 ** (-man - 1))
    a_min_pos =  (2 ** (-(2 ** (exp - 1)) + 1))
    a_min_neg = -(2 ** (-(2 ** (exp - 1)) + 1))
    print(f'min: ±{a_min_pos}\tmax: ±{a_max_pos}')

    # Block box test to get representable numbers
    prev_val=None
    quant_vals=[]
    for i in np.arange(-10,10,0.001):
        a = torch.Tensor([i]).to(device=d)
        quant_a = float_quantize(a, exp=exp, man=man, rounding=r)
        if prev_val!=quant_a[0]:
            quant_vals.append(quant_a[0].item())
            prev_val=quant_a
    print("Values representable in QPytorch")
    print(quant_vals)

    # IEEE-like implementation
    quant_vals=[]
    for sign in [-1,1]:
        exp_offset=(2**(exp-1)-1)
        for e in np.arange(0,2**(exp)):
            m_step=2**(-man)
            for m in np.arange(1,2,m_step):
                if e==0:
                    v=sign*(m-1)
                else:
                    v=sign*2.**(e-exp_offset)*m
                #print(f"sign: {sign} \texp:{e}\t man:{m}\tvalue:{v}")
                quant_vals.append(v)
    print("Values representable in an IEEE-like implementation:")
    print(quant_vals)
    
    # Implementation in QPytorch
    quant_vals=[] 
    for sign in [-1,1]:
        exp_offset=(2**(exp-1))
        for e in np.arange(0,2**(exp)):
            m_step=2**(-man)
            for m in np.arange(1,2,m_step):
                # No denormalized numbers
                if e==0:
                    v=0
                else:
                    v=sign*2.**(e-exp_offset)*m
                #print(f"sign: {sign} \texp:{e-exp_offset}\t man:{m}\tvalue:{v}")
                quant_vals.append(v)
    print("Recreation of values representable in QPytorch")
    print(list(np.sort(quant_vals)))


if __name__ ==  '__main__':
    test_float()

```

**Comment by Tiiiger** [comment]
hi @danielholanda 

1. Yes we did not handle subnorms for simplicity
2. Looks like QPyTorch does not handle values close to 0 correctly. Unfortunately, it could take me a while before getting to this. If you want to submit a PR, I am happy to review and merge it.

**Comment by danielholanda** [comment]
I might have a chance of doing this in the next few weeks and will submit a PR once I'm done.

**Comment by Tiiiger** [comment]
Thanks! Looking forward to the PR.
