### ISSUE TITLE
Is there any way to directly convert fp16 tensors to low precision tensors?

### ISSUE THREAD

**Issue by qysnn** [Tiiiger/QPyTorch#55]
```
>>> half_precision_tensor = torch.rand(5).half()
>>> low_precision_tensor = float_quantize(half_precision_tensor, exp=5, man=2, rounding="nearest")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/users/heyangqin/anaconda3/envs/deepspeed_fp8/lib/python3.9/site-packages/qtorch/quant/quant_function.py", line 283, in float_quantize
    out = quant_module.float_quantize_nearest(x.contiguous(), man, exp)
RuntimeError: expected scalar type Float but found Half
```

**Comment by Tiiiger** [comment]
hi @qysnn ,

unfortunately I don't think so. at the time when we developed thing, half precision wasn't a mature thing in pytorch. 

I also don't think I'll have time to implement this. but feel free to implement it and open a PR!

**Comment by JeevanBhoot** [comment]
Are you still unable to do this? I would like to directly convert torch.bfloat16 tensors to low precision (BFP) tensors. If not, could you guide me to how this could be achieved?
